$schema: "https://json-schema.org/draft/2020-12/schema"
description: Validation schema for config-file

type: object
properties:
  ncbi_api_key:
    type: string
    description: ncbi api-key
  workdir:
    type: string
    description: name of output directory
  method:
    type: string
    enum: ["sample_gtdb", "sample_ncbi", "prune_gtdb"]
    description: sampling strategy to use
  seed:
    type: integer
    description: value for random seed to use in pruning and sampling step
    default: 42
  reannotate_all:
    type: boolean
    description: reannotate all genomes with prokka
    default: false
  required:
    type: string
    description: path to file containing user defined genome accessions to be included in the final dataset
    default: ""

  downloads:
    description: select what type of sequence files to downloads, if all false, workflow will stop after sampling
    properties:
      genomes:
        type: boolean
        default: False
        description: set to True to download genomic sequences of sampled genomes
      cds:
        type: boolean
        default: False
        description: set to True to download nucleotide sequence for genes from sampled genomes
      proteomes:
        type: boolean
        default: False
        description: set to True to download proteins from sampled genomes
      gff3:
        type: boolean
        default: False
        description: set to True to download GFF3 annotations from sampled genomes
    additionalProperties: false

  databases:
    properties:
      blast_genome:
        type: boolean
        default: False
        description: build nucleotide database from genomic sequences
      blast_cds:
        type: boolean
        default: False
        description: build nucleotide database from gene sequences
      blast_protein:
        type: boolean
        default: False
        description: build protein database from proteins
      diamond_protein:
        type: boolean
        default: False
        description: build protein database from proteins using diamond
    additionalProperties: false

  sample_gtdb:
    properties:
      sampling_scheme:
        type: string
        description: path to sampling scheme
      completeness:
        type: number
        description: remove entries with a completeness estimated lower than given value
        default: 0
      contamination:
        type: number
        description: remove entries with a contamination higher than given value
        default: 100
      gtdb_species_representatives:
        type: boolean
        description: keep only entries that are classified as species representetives
        default: False
      version:
        type: number
        enum: [207, 214]
        default: 214
    required: [sampling_scheme, gtdb_species_representatives]
    additionalProperties: false

  sample_ncbi:
    properties:
      sampling_scheme:
        type: string
        description: path to sampling scheme
      database:
        type: string
        description: select database to sample from
        enum: ["RefSeq", "GenBank"]
        default: "GenBank"
    required: [sampling_scheme]
    additionalProperties: false

  prune_gtdb:
    properties:
      bac120:
        type: integer
        default: 0
        description: prune bacterial gtdb-phylogeny until this number of species is remaining
      ar53:
        type: integer
        default: 0
        description: prune archaeal gtdb-phylogeny until this number of species is remaining
      completeness:
        type: number
        description: remove entries with a completeness estimated lower than given value
      contamination:
        type: number
        description: remove entries with a contamination higher than given value
      prune_method:
        type: string
        enum: ["random", "shortest", "longest"]
        default: "shortest"
      version:
        type: number
        enum: [207, 214]
        default: 214
      taxon:
        type: string
        default: ""
    required: [ar53, bac120]
    additionalProperties: false

required: [workdir, method]
additionalProperties: false
